### ISSUE TITLE
Database UNIQUE error

### ISSUE THREAD

**Issue by jmadden173** [jlab-sensing/DirtViz#36]
```
Exception occurred during processing of request from ('172.19.0.4', 47320)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "cell_name_key"
DETAIL:  Key (name)=(cell3) already exists.
```

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "cell_name_key"
DETAIL:  Key (name)=(cell3) already exists.

[SQL: INSERT INTO cell (name, location) VALUES (%(name)s, %(location)s) RETURNING cell.id]
[parameters: {'name': 'cell3', 'location': 'UCSC Farm'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

Will update later with what I believe is happening and the proposed fix for it

**Comment by jmadden173** [comment]
As a temperary fix I am going to remove location tags from chirpstack so that it will use the previous cell for cell3
