### ISSUE TITLE
Bokeh error: SerializationError("can't serialize <class 'decimal.Decimal'>")

### ISSUE THREAD

**Issue by jmadden173** [jlab-sensing/DirtViz#50]
Something is wrong with the newest version of Bokeh (`3.0.1`). Rolling back to `2.4.3` works fine. What's curious is that at least a week ago it was working perfectly fine. Maybe this is due to caching of docker images? Either way, at the moment I don't have time to be able to look into so I'm rolling Bokeh to `2.4.3` and when this inevitably becomes an issue, it can be looked into. For now here's the dump of the logs and version info from trying to run the stack via `docker-compose` on my local machine with commit `d0a21e8060158d3a48d4df6753be98566a93a8bb`.

Version Info
```
Python version      :  3.8.3 (default, Jun  9 2020, 17:39:39) 
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.1
BokehJS static path :  /usr/local/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-6.0.7-arch1-1-x86_64-with-glibc2.2.5
```

Logs Dump
```
dirtviz-portal-1      | 2022-11-08 03:18:47,033 Starting Bokeh server version 3.0.1 (running on Tornado 6.2)
dirtviz-portal-1      | 2022-11-08 03:18:47,196 User authentication hooks NOT provided (default user enabled)
dirtviz-portal-1      | 2022-11-08 03:18:47,199 Bokeh app running at: http://localhost:5006/dirtviz
dirtviz-portal-1      | 2022-11-08 03:18:47,199 Starting Bokeh server with process id: 9
dirtviz-portal-1      | 2022-11-08 03:18:51,985 WebSocket connection opened
dirtviz-portal-1      | 2022-11-08 03:18:51,985 ServerConnection created
dirtviz-portal-1      | 2022-11-08 03:18:52,029 error handling message
dirtviz-portal-1      |  message: Message 'PULL-DOC-REQ' content: {} 
dirtviz-portal-1      |  error: SerializationError("can't serialize <class 'decimal.Decimal'>")
dirtviz-portal-1      | Traceback (most recent call last):
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
dirtviz-portal-1      |     work = await handler(message, connection)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/server/session.py", line 93, in _needs_document_lock_wrapper
dirtviz-portal-1      |     result = func(self, *args, **kwargs)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/server/session.py", line 258, in _handle_pull
dirtviz-portal-1      |     return connection.protocol.create('PULL-DOC-REPLY', message.header['msgid'], self.document)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/protocol/__init__.py", line 135, in create
dirtviz-portal-1      |     return self._messages[msgtype].create(*args, **kwargs)  # type: ignore [attr-defined]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/protocol/messages/pull_doc_reply.py", line 82, in create
dirtviz-portal-1      |     content = PullDoc(doc=document.to_json())
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/document/document.py", line 733, in to_json
dirtviz-portal-1      |     roots = serializer.encode(self._roots)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 275, in _encode
dirtviz-portal-1      |     return self._encode_list(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in _encode_list
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in <listcomp>
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 259, in _encode
dirtviz-portal-1      |     return obj.to_serializable(self)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/model/model.py", line 530, in to_serializable
dirtviz-portal-1      |     super_rep = super().to_serializable(serializer)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 275, in _encode
dirtviz-portal-1      |     return self._encode_list(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in _encode_list
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in <listcomp>
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 259, in _encode
dirtviz-portal-1      |     return obj.to_serializable(self)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/model/model.py", line 530, in to_serializable
dirtviz-portal-1      |     super_rep = super().to_serializable(serializer)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 275, in _encode
dirtviz-portal-1      |     return self._encode_list(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in _encode_list
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in <listcomp>
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 259, in _encode
dirtviz-portal-1      |     return obj.to_serializable(self)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/model/model.py", line 530, in to_serializable
dirtviz-portal-1      |     super_rep = super().to_serializable(serializer)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 275, in _encode
dirtviz-portal-1      |     return self._encode_list(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in _encode_list
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in <listcomp>
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 259, in _encode
dirtviz-portal-1      |     return obj.to_serializable(self)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/model/model.py", line 530, in to_serializable
dirtviz-portal-1      |     super_rep = super().to_serializable(serializer)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 275, in _encode
dirtviz-portal-1      |     return self._encode_list(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in _encode_list
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in <listcomp>
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 259, in _encode
dirtviz-portal-1      |     return obj.to_serializable(self)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/model/model.py", line 530, in to_serializable
dirtviz-portal-1      |     super_rep = super().to_serializable(serializer)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 259, in _encode
dirtviz-portal-1      |     return obj.to_serializable(self)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/model/model.py", line 530, in to_serializable
dirtviz-portal-1      |     super_rep = super().to_serializable(serializer)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in to_serializable
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/has_props.py", line 406, in <dictcomp>
dirtviz-portal-1      |     attributes = {key: serializer.encode(val) for key, val in properties.items()}
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 279, in _encode
dirtviz-portal-1      |     return self._encode_dict(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 335, in _encode_dict
dirtviz-portal-1      |     entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 335, in <listcomp>
dirtviz-portal-1      |     entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 275, in _encode
dirtviz-portal-1      |     return self._encode_list(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in _encode_list
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 318, in <listcomp>
dirtviz-portal-1      |     return [self.encode(item) for item in obj]
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 250, in encode
dirtviz-portal-1      |     return self._encode(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 291, in _encode
dirtviz-portal-1      |     return self._encode_other(obj)
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 459, in _encode_other
dirtviz-portal-1      |     self.error(f"can't serialize {type(obj)}")
dirtviz-portal-1      |   File "/usr/local/lib/python3.8/site-packages/bokeh/core/serialization.py", line 462, in error
dirtviz-portal-1      |     raise SerializationError(message)
dirtviz-portal-1      | bokeh.core.serialization.SerializationError: can't serialize <class 'decimal.Decimal'>
```

**Comment by jmadden173** [comment]
Accidentally close while apply hotfix
